#!/usr/bin/env bun
/**
 * Centralized type generation script for HyperDown.
 *
 * Compiles each JSON Schema entry below with `json-schema-to-typescript`'s
 * in-process API and writes the result with our auto-generated banner. Using the
 * library directly (instead of the `json2ts` bin via `bunx`) avoids resolving an
 * unrelated, stale `json2ts` package and works offline/in sandboxed builds.
 *
 * Usage:
 *   bun scripts/gen-types.ts
 */

import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { compileFromFile } from "json-schema-to-typescript";

import { scriptLog } from "../src/utils/logger.server.ts";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

const BANNER = `/* oxlint-disable */
/* oxfmt-disable */
/**
 * --------------------------------------------------------
 *  HyperDown Auto-Generated Types
 * --------------------------------------------------------
 *  This file was automatically generated by HyperDown.
 *  DO NOT EDIT THIS FILE DIRECTLY.
 *
 *  To modify these types, update the corresponding
 *  schema file and run: bun run gen:types
 * --------------------------------------------------------
 */
`;

/** Each entry maps a JSON Schema file to its TypeScript output file. */
const schemas = [
  {
    input: "schemas/frontmatter.schema.json",
    output: "src/frontmatter/schema-types.ts",
    description: "Front Matter CMS config types",
  },
  {
    input: "schemas/hyperdown.config.schema.json",
    output: "src/utils/types.ts",
    description: "HyperDown runtime config types",
  },
] as const;

async function runCodegen(input: string, output: string): Promise<void> {
  const absInput = resolve(ROOT, input);
  const absOutput = resolve(ROOT, output);

  const ts = await compileFromFile(absInput, {
    additionalProperties: false,
    bannerComment: BANNER,
    cwd: dirname(absInput),
  });

  writeFileSync(absOutput, ts);
}

// Each schema spawns an independent `json-schema-to-typescript` subprocess
// writing to a distinct output file, so they have no ordering dependency and
// run concurrently. `allSettled` lets every task finish even if one fails.
const results = await Promise.allSettled(
  schemas.map(async ({ input, output, description }) => {
    scriptLog.info(`Generating types for ${description}: ${input} → ${output}`);
    await runCodegen(input, output);
    scriptLog.info(`✅ Done: ${output}`);
  }),
);

let hasError = false;
for (const result of results) {
  if (result.status === "rejected") {
    scriptLog.error(`❌ Failed: ${(result.reason as Error).message}`);
    hasError = true;
  }
}

if (hasError) {
  scriptLog.error("Type generation completed with errors.");
  process.exit(1);
} else {
  scriptLog.info("All types generated successfully.");
}
