// Shared string templates emitted into consuming apps' generated files. Kept in
// one place so the Vite-side codegen and the Next adapter share a single banner
// source instead of each carrying their own copy.

/** Lint/format suppression prefix prepended to every generated file. */
export const GENERATED_PRAGMA = "/* oxlint-disable */\n/* oxfmt-disable */\n";

/* oxfmt-ignore */
/** Full banner for HyperDown-generated TypeScript (types / builder / modules). */
export const GENERATED_BANNER = GENERATED_PRAGMA + "/**\n * --------------------------------------------------------\n *  HyperDown Auto-Generated Types\n * --------------------------------------------------------\n *  This file was automatically generated by HyperDown.\n *  DO NOT EDIT THIS FILE DIRECTLY.\n *\n *  To modify these types, update the corresponding\n *  frontmatter.json file and rebuild the project.\n * --------------------------------------------------------\n */\n\n";

/** Banner for the Next.js `modules.ts` (explicit `@next/mdx` imports — no Vite glob). */
export const NEXT_MODULES_BANNER =
  GENERATED_PRAGMA + "// Auto-generated for Next.js (explicit @next/mdx imports — no Vite glob).\n";

const CONTENT_MODULE_MAP_TYPE = `import type { ContentModuleMap } from "@indago/hyper-down/types";\n\n`;

/**
 * Full Next.js `modules.ts` content: banner + explicit `@next/mdx` import lines +
 * the `ContentModuleMap` default export. `imports`/`entries` are pre-built source
 * lines (one per MDX file); an empty set yields an empty map.
 */
export function nextModulesFile(imports: string[], entries: string[]): string {
  const map =
    imports.length > 0
      ? `${imports.join("\n")}\n\n${CONTENT_MODULE_MAP_TYPE}export default {\n${entries.join("\n")}\n} as unknown as ContentModuleMap;\n`
      : `${CONTENT_MODULE_MAP_TYPE}export default {} as ContentModuleMap;\n`;
  return NEXT_MODULES_BANNER + map;
}
