/* oxlint-disable */
/* oxfmt-disable */
/**
 * --------------------------------------------------------
 *  HyperJson Auto-Generated Types
 * --------------------------------------------------------
 *  This file was automatically generated by HyperJson.
 *  DO NOT EDIT THIS FILE DIRECTLY.
 *
 *  To modify these types, update the corresponding
 *  schema file and run: bun run gen:types
 * --------------------------------------------------------
 */

/**
 * Configuration file for HyperJson — JSON content validation and type generation.
 */
export interface HyperJsonConfiguration {
  /**
   * Path to the JSON schema file for IDE intellisense.
   */
  $schema?: string;
  /**
   * Base directory for JSON content files, relative to the app root.
   */
  contentDir: string;
  /**
   * Options that control how content validation behaves.
   */
  validation?: {
    /**
     * Fail on additional properties not defined in the schema.
     */
    strict?: boolean;
    /**
     * Exit with a non-zero code when any validation error is found.
     */
    failOnError?: boolean;
  };
}
