/* oxlint-disable */
/* oxfmt-disable */
/**
 * --------------------------------------------------------
 *  HyperDown Auto-Generated Types
 * --------------------------------------------------------
 *  This file was automatically generated by HyperDown.
 *  DO NOT EDIT THIS FILE DIRECTLY.
 *
 *  To modify these types, update the corresponding
 *  schema file and run: bun run gen:types
 * --------------------------------------------------------
 */

/**
 * Defines the settings for Front Matter
 */
export interface FrontMatterTeamSettings {
  "frontMatter.projects"?: {
    name?: string;
    default?: boolean;
    configuration?: FrontMatterTeamSettings1;
  }[];
  "frontMatter.extensibility.scripts"?: string[];
  "frontMatter.experimental"?: boolean;
  "frontMatter.extends"?: string[];
  "frontMatter.config.dynamicFilePath"?: string;
  "frontMatter.content.autoUpdateDate"?: boolean;
  "frontMatter.content.defaultFileType"?: (("md" | "mdx") | string) & string;
  "frontMatter.content.defaultSorting"?: (
    | ("LastModifiedAsc" | "LastModifiedDesc" | "FileNameAsc" | "FileNameDesc")
    | string
  ) &
    string;
  "frontMatter.content.draftField"?: {
    /**
     * Type of the draft field you want to use
     */
    type: "boolean" | "choice";
    /**
     * Name of the field to use
     */
    name: string;
    /**
     * By default the draft field is set to true when the content is a draft. Set this to true to set it to false.
     */
    invert?: boolean;
    /**
     * List of choices for the field
     */
    choices?: string[];
  };
  "frontMatter.content.fmHighlight"?: boolean;
  "frontMatter.content.hideFm"?: boolean;
  "frontMatter.content.hideFmMessage"?: string;
  "frontMatter.content.pageFolders"?: {
    /**
     * Name of the folder
     */
    title: string;
    /**
     * Path of the folder
     */
    path: string;
    /**
     * Exclude sub-directories
     */
    excludeSubdir?: boolean;
    /**
     * Exclude paths (e.g. api, _*.*)
     */
    excludePaths?: boolean & string[];
    /**
     * Defines a custom preview path for the folder.
     */
    previewPath?: null | string;
    /**
     * Specify if you want to add a trailing slash to the preview URL.
     */
    trailingSlash?: boolean;
    /**
     * Defines a prefix for the file name.
     */
    filePrefix?: null | string;
    /**
     * Defines which content types can be used for the current location. If not defined, all content types will be available.
     */
    contentTypes?: string[];
    /**
     * Disable the creation of new content in the folder.
     */
    disableCreation?: boolean;
    /**
     * Set the default locale ID for the page folder. All content from this folder is translatable to the languages defined in the `frontMatter.content.i18n` setting.
     */
    defaultLocale?: string;
    /**
     * Define the locales for the page folder. This will be used for the translation of the content.
     */
    locales?: {
      title?: string;
      locale?: string;
      path?: string;
    }[];
  }[];
  "frontMatter.content.i18n"?: {
    /**
     * Title of the locale
     */
    title?: string;
    /**
     * Locale code
     */
    locale: string;
    /**
     * Relative path of the locale folder
     */
    path: string;
  }[];
  "frontMatter.content.placeholders"?: {
    /**
     * ID of the placeholder, in your content type or template, use it as follows: {{placeholder}}
     */
    id: string;
    /**
     * The placeholder its value
     */
    value?: string;
    /**
     * The script to execute to get the value of the placeholder
     */
    script?: string;
    command?: {
      [k: string]: unknown;
    };
  }[];
  "frontMatter.content.publicFolder"?:
    | string
    | {
        /**
         * Specify the path of the assets folder
         */
        path?: string;
        /**
         * Defines if the path to your media files be relative to the content file?
         */
        relative?: boolean;
      };
  "frontMatter.snippets.wrapper.enabled"?: boolean;
  "frontMatter.content.snippets"?: {
    [k: string]: {
      body: string | string[];
      /**
       * The snippet title.
       */
      title?: string;
      /**
       * The snippet description.
       */
      description?: string;
      fields?: {
        [k: string]: unknown;
      };
      /**
       * The snippet opening tags.
       */
      openingTags?: string;
      /**
       * The snippet closing tags.
       */
      closingTags?: string;
      /**
       * Specify if the snippet is to be used for media files.
       */
      isMediaSnippet?: boolean;
    };
  };
  "frontMatter.content.grouping"?: {
    /**
     * The ID of the grouping option.
     */
    id?: string;
    /**
     * Title of the grouping which will be shown in the UI.
     */
    title: string;
    /**
     * Name of the content-type field to group by.
     */
    name: string;
  }[];
  "frontMatter.content.sorting"?: {
    /**
     * The ID of the sorting option. This will be used for the storing the last used sorting option or the default option.
     */
    id?: string;
    /**
     * Name of the sorting label
     */
    title: string;
    /**
     * Name of the metadata field to sort by
     */
    name: string;
    /**
     * Order of the sorting
     */
    order: "asc" | "desc";
    /**
     * Type of the field value
     */
    type?: "string" | "date" | "number";
  }[];
  "frontMatter.content.supportedFileTypes"?: string[];
  "frontMatter.content.wysiwyg"?: boolean;
  "frontMatter.content.filters"?:
    | []
    | ["contentFolders" | "tags" | "categories"]
    | [
        "contentFolders" | "tags" | "categories",
        {
          title?: string;
          name?: string;
        },
      ];
  "frontMatter.custom.scripts"?: {
    /**
     * ID of the script.
     */
    id?: string;
    /**
     * Title you want to give to your script. Will be shown as the title of the button.
     */
    title: string;
    /**
     * Path to the script to execute
     */
    script: string;
    /**
     * Path to the node executable. This is required when using NVM, so that there is no confusion of which node version to use. (deprecated: use the command property instead)
     */
    nodeBin?: string;
    /**
     * Run the script for all content files
     */
    bulk?: boolean;
    /**
     * Define where you want to output your script output. Default is a notification, but you can specify to show it in an editor panel.
     */
    output?: "editor" | "notification";
    /**
     * The type of output for the editor panel. Can be used to change it to 'markdown' for example
     */
    outputType?: string;
    /**
     * The type for which the script will be used.
     */
    type?: "content" | "mediaFolder" | "mediaFile";
    /**
     * The type of script you want to execute.
     */
    command?: (("node" | "bash" | "powershell" | "python" | "python3") | string) & string;
    /**
     * Hide the action from the UI
     */
    hidden?: boolean;
    environments?: {
      /**
       * The environment type for which the script needs to be used
       */
      type?: "macos" | "linux" | "windows";
      /**
       * Path to the script to execute
       */
      script?: string;
      command?: {
        [k: string]: unknown;
      };
    }[];
    /**
     * Define the content types for which the script will be used. If none are defined, it will be available to all types.
     */
    contentTypes?: string[];
  }[];
  "frontMatter.dashboard.content.pagination"?: boolean | number;
  "frontMatter.dashboard.content.cardTags"?: string;
  "frontMatter.dashboard.content.card.fields.state"?: boolean;
  "frontMatter.dashboard.content.card.fields.date"?: boolean;
  "frontMatter.dashboard.content.card.fields.description"?: null | string;
  "frontMatter.dashboard.content.card.fields.title"?: null | string;
  "frontMatter.dashboard.openOnStart"?: boolean | null;
  "frontMatter.data.files"?: {
    [k: string]: unknown;
  }[];
  "frontMatter.data.folders"?: {
    [k: string]: unknown;
  }[];
  "frontMatter.data.types"?: {
    /**
     * Your unique ID you want to use for your data type.
     */
    id: string;
    schema: {
      [k: string]: unknown;
    };
  }[];
  "frontMatter.file.preserveCasing"?: boolean;
  "frontMatter.framework.id"?: string;
  "frontMatter.framework.startCommand"?: string | null;
  "frontMatter.git.enabled"?: boolean;
  "frontMatter.git.commitMessage"?: string;
  "frontMatter.git.disableOnBranches"?: string[];
  "frontMatter.git.requiresCommitMessage"?: string[];
  "frontMatter.git.submodule.pull"?: boolean;
  "frontMatter.git.submodule.push"?: boolean;
  "frontMatter.git.submodule.branch"?: string;
  "frontMatter.git.submodule.folder"?: string;
  "frontMatter.global.activeMode"?: string | null;
  "frontMatter.global.modes"?: {
    /**
     * The ID of your mode.
     */
    id: string;
    /**
     * The features you want to use for your mode.
     */
    features: (
      | "panel.globalSettings"
      | "panel.seo"
      | "panel.actions"
      | "panel.metadata"
      | "panel.contentType"
      | "panel.gitActions"
      | "panel.recentlyModified"
      | "panel.otherActions"
      | "dashboard.snippets.view"
      | "dashboard.snippets.manage"
      | "dashboard.data.view"
      | "dashboard.taxonomy.view"
    )[];
  }[];
  "frontMatter.global.notifications"?: ("info" | "warning" | "error")[];
  "frontMatter.global.disabledNotifications"?: unknown[];
  "frontMatter.global.timezone"?: string;
  "frontMatter.media.defaultSorting"?:
    | "LastModifiedAsc"
    | "LastModifiedDesc"
    | "FileNameAsc"
    | "FileNameDesc";
  "frontMatter.media.contentTypes"?:
    | {
        /**
         * Name of the media content type
         */
        name?: string;
        /**
         * Specify the file types to allow for the media content type
         */
        fileTypes?: string[];
        /**
         * Define the fields of the media content type
         */
        fields?: {
          /**
           * Title to show in the UI
           */
          title?: string;
          /**
           * Name of the field to use
           */
          name?: string;
          /**
           * Define the type of field
           */
          type?: "string";
          /**
           * Is a single line field
           */
          single?: boolean;
        }[];
      }[]
    | null;
  "frontMatter.media.supportedMimeTypes"?: string[];
  "frontMatter.panel.openOnSupportedFile"?: boolean;
  "frontMatter.panel.freeform"?: boolean;
  "frontMatter.panel.actions.disabled"?: (
    | "openDashboard"
    | "createContent"
    | "optimizeSlug"
    | "preview"
    | "openOnWebsite"
    | "startStopServer"
    | "customActions"
  )[];
  "frontMatter.preview.host"?: string;
  "frontMatter.preview.pathName"?: string;
  "frontMatter.preview.trailingSlash"?: boolean & string;
  "frontMatter.site.baseURL"?: string;
  "frontMatter.taxonomy.alignFilename"?: boolean;
  "frontMatter.taxonomy.categories"?: string[];
  "frontMatter.taxonomy.commaSeparatedFields"?: string[];
  "frontMatter.taxonomy.contentTypes"?:
    | {
        /**
         * Define the type of field
         */
        name: string;
        /**
         * Specifies the type of content you want to create.
         */
        fileType?: (("md" | "mdx") | string) & string;
        /**
         * Specify if the empty values should be cleared.
         */
        clearEmpty?: boolean;
        /**
         * Specify if the content type can be used as sub content.
         */
        allowAsSubContent?: boolean;
        /**
         * Specify if the content type is sub content.
         */
        isSubContent?: boolean;
        /**
         * Define the fields of the content type
         */
        fields: {
          [k: string]: unknown;
        }[];
        /**
         * Specify if you want to create a folder when creating new content.
         */
        pageBundle?: boolean;
        /**
         * Defines a custom preview path for the content type.
         */
        previewPath?: null | string;
        /**
         * Specify if you want to add a trailing slash to the preview URL.
         */
        trailingSlash?: boolean;
        /**
         * Defines a custom slug template.
         */
        slugTemplate?: null | string;
        /**
         * An optional template that can be used for creating new content.
         */
        template?: string;
        /**
         * An optional post script that can be used after new content creation.
         */
        postScript?: string;
        /**
         * Defines a prefix for the file name.
         */
        filePrefix?: null | string;
        /**
         * Default file name to use when creating new content.
         */
        defaultFileName?: string;
      }[]
    | null;
  "frontMatter.taxonomy.customTaxonomy"?: {
    /**
     * ID for your taxonomy field. It cannot contain the "tags" or "categories" value.
     */
    id: string;
    /**
     * Options from which you can pick.
     */
    options: string[];
  }[];
  "frontMatter.taxonomy.dateFormat"?: string;
  "frontMatter.taxonomy.fieldGroups"?: {
    /**
     * The name of the field group
     */
    id: string;
    /**
     * The name of the field to be used as display value
     */
    labelField?: string;
    fields: {
      [k: string]: unknown;
    };
  }[];
  "frontMatter.taxonomy.frontMatterType"?: "YAML" | "TOML" | "JSON";
  "frontMatter.taxonomy.indentArrays"?: boolean;
  "frontMatter.taxonomy.quoteStringValues"?: boolean;
  "frontMatter.taxonomy.noPropertyValueQuotes"?: string[];
  "frontMatter.taxonomy.seoContentLengh"?: number;
  "frontMatter.taxonomy.seoDescriptionField"?: string;
  "frontMatter.taxonomy.seoDescriptionLength"?: number;
  "frontMatter.taxonomy.seoSlugLength"?: number;
  "frontMatter.taxonomy.seoTitleField"?: string;
  "frontMatter.taxonomy.seoTitleLength"?: number;
  "frontMatter.taxonomy.slugPrefix"?: string;
  "frontMatter.taxonomy.slugSuffix"?: string;
  "frontMatter.taxonomy.slugTemplate"?: string | null;
  "frontMatter.taxonomy.tags"?: string[];
  "frontMatter.templates.enabled"?: boolean;
  "frontMatter.templates.folder"?: string;
  "frontMatter.templates.prefix"?: string;
  "frontMatter.validation.enabled"?: boolean;
  "frontMatter.website.host"?: string;
  "frontMatter.logging"?: "error" | "warn" | "info" | "verbose";
  "frontMatter.copilot.family"?: string;
  "frontMatter.copilot.enabled"?: boolean;
}
/**
 * Defines the settings for Front Matter
 */
export interface FrontMatterTeamSettings1 {
  "frontMatter.projects"?: {
    name?: string;
    default?: boolean;
    configuration?: FrontMatterTeamSettings1;
  }[];
  "frontMatter.extensibility.scripts"?: string[];
  "frontMatter.experimental"?: boolean;
  "frontMatter.extends"?: string[];
  "frontMatter.config.dynamicFilePath"?: string;
  "frontMatter.content.autoUpdateDate"?: boolean;
  "frontMatter.content.defaultFileType"?: (("md" | "mdx") | string) & string;
  "frontMatter.content.defaultSorting"?: (
    | ("LastModifiedAsc" | "LastModifiedDesc" | "FileNameAsc" | "FileNameDesc")
    | string
  ) &
    string;
  "frontMatter.content.draftField"?: {
    /**
     * Type of the draft field you want to use
     */
    type: "boolean" | "choice";
    /**
     * Name of the field to use
     */
    name: string;
    /**
     * By default the draft field is set to true when the content is a draft. Set this to true to set it to false.
     */
    invert?: boolean;
    /**
     * List of choices for the field
     */
    choices?: string[];
  };
  "frontMatter.content.fmHighlight"?: boolean;
  "frontMatter.content.hideFm"?: boolean;
  "frontMatter.content.hideFmMessage"?: string;
  "frontMatter.content.pageFolders"?: {
    /**
     * Name of the folder
     */
    title: string;
    /**
     * Path of the folder
     */
    path: string;
    /**
     * Exclude sub-directories
     */
    excludeSubdir?: boolean;
    /**
     * Exclude paths (e.g. api, _*.*)
     */
    excludePaths?: boolean & string[];
    /**
     * Defines a custom preview path for the folder.
     */
    previewPath?: null | string;
    /**
     * Specify if you want to add a trailing slash to the preview URL.
     */
    trailingSlash?: boolean;
    /**
     * Defines a prefix for the file name.
     */
    filePrefix?: null | string;
    /**
     * Defines which content types can be used for the current location. If not defined, all content types will be available.
     */
    contentTypes?: string[];
    /**
     * Disable the creation of new content in the folder.
     */
    disableCreation?: boolean;
    /**
     * Set the default locale ID for the page folder. All content from this folder is translatable to the languages defined in the `frontMatter.content.i18n` setting.
     */
    defaultLocale?: string;
    /**
     * Define the locales for the page folder. This will be used for the translation of the content.
     */
    locales?: {
      title?: string;
      locale?: string;
      path?: string;
    }[];
  }[];
  "frontMatter.content.i18n"?: {
    /**
     * Title of the locale
     */
    title?: string;
    /**
     * Locale code
     */
    locale: string;
    /**
     * Relative path of the locale folder
     */
    path: string;
  }[];
  "frontMatter.content.placeholders"?: {
    /**
     * ID of the placeholder, in your content type or template, use it as follows: {{placeholder}}
     */
    id: string;
    /**
     * The placeholder its value
     */
    value?: string;
    /**
     * The script to execute to get the value of the placeholder
     */
    script?: string;
    command?: {
      [k: string]: unknown;
    };
  }[];
  "frontMatter.content.publicFolder"?:
    | string
    | {
        /**
         * Specify the path of the assets folder
         */
        path?: string;
        /**
         * Defines if the path to your media files be relative to the content file?
         */
        relative?: boolean;
      };
  "frontMatter.snippets.wrapper.enabled"?: boolean;
  "frontMatter.content.snippets"?: {
    [k: string]: {
      body: string | string[];
      /**
       * The snippet title.
       */
      title?: string;
      /**
       * The snippet description.
       */
      description?: string;
      fields?: {
        [k: string]: unknown;
      };
      /**
       * The snippet opening tags.
       */
      openingTags?: string;
      /**
       * The snippet closing tags.
       */
      closingTags?: string;
      /**
       * Specify if the snippet is to be used for media files.
       */
      isMediaSnippet?: boolean;
    };
  };
  "frontMatter.content.grouping"?: {
    /**
     * The ID of the grouping option.
     */
    id?: string;
    /**
     * Title of the grouping which will be shown in the UI.
     */
    title: string;
    /**
     * Name of the content-type field to group by.
     */
    name: string;
  }[];
  "frontMatter.content.sorting"?: {
    /**
     * The ID of the sorting option. This will be used for the storing the last used sorting option or the default option.
     */
    id?: string;
    /**
     * Name of the sorting label
     */
    title: string;
    /**
     * Name of the metadata field to sort by
     */
    name: string;
    /**
     * Order of the sorting
     */
    order: "asc" | "desc";
    /**
     * Type of the field value
     */
    type?: "string" | "date" | "number";
  }[];
  "frontMatter.content.supportedFileTypes"?: string[];
  "frontMatter.content.wysiwyg"?: boolean;
  "frontMatter.content.filters"?:
    | []
    | ["contentFolders" | "tags" | "categories"]
    | [
        "contentFolders" | "tags" | "categories",
        {
          title?: string;
          name?: string;
        },
      ];
  "frontMatter.custom.scripts"?: {
    /**
     * ID of the script.
     */
    id?: string;
    /**
     * Title you want to give to your script. Will be shown as the title of the button.
     */
    title: string;
    /**
     * Path to the script to execute
     */
    script: string;
    /**
     * Path to the node executable. This is required when using NVM, so that there is no confusion of which node version to use. (deprecated: use the command property instead)
     */
    nodeBin?: string;
    /**
     * Run the script for all content files
     */
    bulk?: boolean;
    /**
     * Define where you want to output your script output. Default is a notification, but you can specify to show it in an editor panel.
     */
    output?: "editor" | "notification";
    /**
     * The type of output for the editor panel. Can be used to change it to 'markdown' for example
     */
    outputType?: string;
    /**
     * The type for which the script will be used.
     */
    type?: "content" | "mediaFolder" | "mediaFile";
    /**
     * The type of script you want to execute.
     */
    command?: (("node" | "bash" | "powershell" | "python" | "python3") | string) & string;
    /**
     * Hide the action from the UI
     */
    hidden?: boolean;
    environments?: {
      /**
       * The environment type for which the script needs to be used
       */
      type?: "macos" | "linux" | "windows";
      /**
       * Path to the script to execute
       */
      script?: string;
      command?: {
        [k: string]: unknown;
      };
    }[];
    /**
     * Define the content types for which the script will be used. If none are defined, it will be available to all types.
     */
    contentTypes?: string[];
  }[];
  "frontMatter.dashboard.content.pagination"?: boolean | number;
  "frontMatter.dashboard.content.cardTags"?: string;
  "frontMatter.dashboard.content.card.fields.state"?: boolean;
  "frontMatter.dashboard.content.card.fields.date"?: boolean;
  "frontMatter.dashboard.content.card.fields.description"?: null | string;
  "frontMatter.dashboard.content.card.fields.title"?: null | string;
  "frontMatter.dashboard.openOnStart"?: boolean | null;
  "frontMatter.data.files"?: {
    [k: string]: unknown;
  }[];
  "frontMatter.data.folders"?: {
    [k: string]: unknown;
  }[];
  "frontMatter.data.types"?: {
    /**
     * Your unique ID you want to use for your data type.
     */
    id: string;
    schema: {
      [k: string]: unknown;
    };
  }[];
  "frontMatter.file.preserveCasing"?: boolean;
  "frontMatter.framework.id"?: string;
  "frontMatter.framework.startCommand"?: string | null;
  "frontMatter.git.enabled"?: boolean;
  "frontMatter.git.commitMessage"?: string;
  "frontMatter.git.disableOnBranches"?: string[];
  "frontMatter.git.requiresCommitMessage"?: string[];
  "frontMatter.git.submodule.pull"?: boolean;
  "frontMatter.git.submodule.push"?: boolean;
  "frontMatter.git.submodule.branch"?: string;
  "frontMatter.git.submodule.folder"?: string;
  "frontMatter.global.activeMode"?: string | null;
  "frontMatter.global.modes"?: {
    /**
     * The ID of your mode.
     */
    id: string;
    /**
     * The features you want to use for your mode.
     */
    features: (
      | "panel.globalSettings"
      | "panel.seo"
      | "panel.actions"
      | "panel.metadata"
      | "panel.contentType"
      | "panel.gitActions"
      | "panel.recentlyModified"
      | "panel.otherActions"
      | "dashboard.snippets.view"
      | "dashboard.snippets.manage"
      | "dashboard.data.view"
      | "dashboard.taxonomy.view"
    )[];
  }[];
  "frontMatter.global.notifications"?: ("info" | "warning" | "error")[];
  "frontMatter.global.disabledNotifications"?: unknown[];
  "frontMatter.global.timezone"?: string;
  "frontMatter.media.defaultSorting"?:
    | "LastModifiedAsc"
    | "LastModifiedDesc"
    | "FileNameAsc"
    | "FileNameDesc";
  "frontMatter.media.contentTypes"?:
    | {
        /**
         * Name of the media content type
         */
        name?: string;
        /**
         * Specify the file types to allow for the media content type
         */
        fileTypes?: string[];
        /**
         * Define the fields of the media content type
         */
        fields?: {
          /**
           * Title to show in the UI
           */
          title?: string;
          /**
           * Name of the field to use
           */
          name?: string;
          /**
           * Define the type of field
           */
          type?: "string";
          /**
           * Is a single line field
           */
          single?: boolean;
        }[];
      }[]
    | null;
  "frontMatter.media.supportedMimeTypes"?: string[];
  "frontMatter.panel.openOnSupportedFile"?: boolean;
  "frontMatter.panel.freeform"?: boolean;
  "frontMatter.panel.actions.disabled"?: (
    | "openDashboard"
    | "createContent"
    | "optimizeSlug"
    | "preview"
    | "openOnWebsite"
    | "startStopServer"
    | "customActions"
  )[];
  "frontMatter.preview.host"?: string;
  "frontMatter.preview.pathName"?: string;
  "frontMatter.preview.trailingSlash"?: boolean & string;
  "frontMatter.site.baseURL"?: string;
  "frontMatter.taxonomy.alignFilename"?: boolean;
  "frontMatter.taxonomy.categories"?: string[];
  "frontMatter.taxonomy.commaSeparatedFields"?: string[];
  "frontMatter.taxonomy.contentTypes"?:
    | {
        /**
         * Define the type of field
         */
        name: string;
        /**
         * Specifies the type of content you want to create.
         */
        fileType?: (("md" | "mdx") | string) & string;
        /**
         * Specify if the empty values should be cleared.
         */
        clearEmpty?: boolean;
        /**
         * Specify if the content type can be used as sub content.
         */
        allowAsSubContent?: boolean;
        /**
         * Specify if the content type is sub content.
         */
        isSubContent?: boolean;
        /**
         * Define the fields of the content type
         */
        fields: {
          [k: string]: unknown;
        }[];
        /**
         * Specify if you want to create a folder when creating new content.
         */
        pageBundle?: boolean;
        /**
         * Defines a custom preview path for the content type.
         */
        previewPath?: null | string;
        /**
         * Specify if you want to add a trailing slash to the preview URL.
         */
        trailingSlash?: boolean;
        /**
         * Defines a custom slug template.
         */
        slugTemplate?: null | string;
        /**
         * An optional template that can be used for creating new content.
         */
        template?: string;
        /**
         * An optional post script that can be used after new content creation.
         */
        postScript?: string;
        /**
         * Defines a prefix for the file name.
         */
        filePrefix?: null | string;
        /**
         * Default file name to use when creating new content.
         */
        defaultFileName?: string;
      }[]
    | null;
  "frontMatter.taxonomy.customTaxonomy"?: {
    /**
     * ID for your taxonomy field. It cannot contain the "tags" or "categories" value.
     */
    id: string;
    /**
     * Options from which you can pick.
     */
    options: string[];
  }[];
  "frontMatter.taxonomy.dateFormat"?: string;
  "frontMatter.taxonomy.fieldGroups"?: {
    /**
     * The name of the field group
     */
    id: string;
    /**
     * The name of the field to be used as display value
     */
    labelField?: string;
    fields: {
      [k: string]: unknown;
    };
  }[];
  "frontMatter.taxonomy.frontMatterType"?: "YAML" | "TOML" | "JSON";
  "frontMatter.taxonomy.indentArrays"?: boolean;
  "frontMatter.taxonomy.quoteStringValues"?: boolean;
  "frontMatter.taxonomy.noPropertyValueQuotes"?: string[];
  "frontMatter.taxonomy.seoContentLengh"?: number;
  "frontMatter.taxonomy.seoDescriptionField"?: string;
  "frontMatter.taxonomy.seoDescriptionLength"?: number;
  "frontMatter.taxonomy.seoSlugLength"?: number;
  "frontMatter.taxonomy.seoTitleField"?: string;
  "frontMatter.taxonomy.seoTitleLength"?: number;
  "frontMatter.taxonomy.slugPrefix"?: string;
  "frontMatter.taxonomy.slugSuffix"?: string;
  "frontMatter.taxonomy.slugTemplate"?: string | null;
  "frontMatter.taxonomy.tags"?: string[];
  "frontMatter.templates.enabled"?: boolean;
  "frontMatter.templates.folder"?: string;
  "frontMatter.templates.prefix"?: string;
  "frontMatter.validation.enabled"?: boolean;
  "frontMatter.website.host"?: string;
  "frontMatter.logging"?: "error" | "warn" | "info" | "verbose";
  "frontMatter.copilot.family"?: string;
  "frontMatter.copilot.enabled"?: boolean;
}
