#!/usr/bin/env bun
/**
 * Centralized type generation script for HyperJson.
 *
 * Compiles each JSON Schema entry below with `json-schema-to-typescript`'s
 * in-process API and writes the result with our auto-generated banner. Mirrors
 * the structure of `packages/HyperDown/scripts/gen-types.ts`. Using the library
 * directly (instead of the `json2ts` bin via `bunx`) avoids resolving an
 * unrelated, stale `json2ts` package and works offline/in sandboxed builds.
 *
 * Usage:
 *   bun scripts/gen-types.ts
 */

import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { compileFromFile } from "json-schema-to-typescript";

import { log as scriptLog } from "../src/lib/logger.ts";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

// oxfmt-ignore
const BANNER = "/* oxlint-disable */\n/* oxfmt-disable */\n/**\n * --------------------------------------------------------\n *  HyperJson Auto-Generated Types\n * --------------------------------------------------------\n *  This file was automatically generated by HyperJson.\n *  DO NOT EDIT THIS FILE DIRECTLY.\n *\n *  To modify these types, update the corresponding\n *  schema file and run: bun run gen:types\n * --------------------------------------------------------\n */\n\n";

/** Each entry maps a JSON Schema file to its TypeScript output file. */
const schemas = [
  {
    input: "schemas/hyperjson.config.schema.json",
    output: "src/lib/types.ts",
    description: "HyperJson runtime config types",
  },
] as const;

async function runCodegen(input: string, output: string): Promise<void> {
  const absInput = resolve(ROOT, input);
  const absOutput = resolve(ROOT, output);

  const ts = await compileFromFile(absInput, {
    additionalProperties: false,
    bannerComment: BANNER,
    cwd: dirname(absInput),
  });

  writeFileSync(absOutput, ts);
}

let hasError = false;

for (const { input, output, description } of schemas) {
  scriptLog.info(`Generating types for ${description}: ${input} → ${output}`);

  try {
    await runCodegen(input, output);
    scriptLog.info(`✅ Done: ${output}`);
  } catch (err) {
    scriptLog.error(`❌ Failed: ${(err as Error).message}`);
    hasError = true;
  }
}

if (hasError) {
  scriptLog.error("Type generation completed with errors.");
  process.exit(1);
} else {
  scriptLog.info("All types generated successfully.");
}
