/* oxlint-disable */
/* oxfmt-disable */
/**
 * --------------------------------------------------------
 *  HyperDown Auto-Generated Types
 * --------------------------------------------------------
 *  This file was automatically generated by HyperDown.
 *  DO NOT EDIT THIS FILE DIRECTLY.
 *
 *  To modify these types, update the corresponding
 *  schema file and run: bun run gen:types
 * --------------------------------------------------------
 */

/**
 * Schema for hyperdown.config.json — centralized configuration for database generation, sitemap, and i18n.
 */
export interface HyperDownConfiguration {
  /**
   * Path to the JSON schema file for IDE intellisense.
   */
  $schema?: string;
  /**
   * SQLite database generation configuration.
   */
  database: {
    /**
     * The base directory for all content, relative to the app working directory.
     */
    contentDir: string;
    /**
     * Absolute or relative path to the frontmatter.json file.
     */
    frontmatterJsonPath: string;
    /**
     * Output path for the generated SQLite database, relative to the config file.
     */
    outputPath?: string;
  };
  /**
   * Sitemap generation configuration.
   */
  sitemap: {
    /**
     * Base URL of the site (no trailing slash).
     */
    siteUrl: string;
    /**
     * Relative path from this config file to the output sitemap.xml.
     */
    outputPath: string;
    /**
     * Static routes to include in the sitemap.
     */
    staticRoutes: SitemapRoute[];
    /**
     * Content types to scan for dynamic sitemap entries.
     */
    contentTypes: SitemapContentType[];
  };
  /**
   * Internationalization configuration.
   */
  i18n: {
    /**
     * The default locale code (e.g. 'en').
     */
    defaultLocale: string;
    /**
     * All supported locale codes.
     */
    locales: string[];
    /**
     * The i18n detection strategy (currently supports folder).
     */
    strategy: "folder";
    /**
     * File pattern for i18n detection.
     */
    filePattern?: {};
  };
}
/**
 * A static route entry for the sitemap.
 */
export interface SitemapRoute {
  /**
   * URL path relative to siteUrl.
   */
  path: string;
  /**
   * Priority value between 0.0 and 1.0.
   */
  priority: string;
  /**
   * How frequently the page is likely to change.
   */
  changefreq: "always" | "hourly" | "daily" | "weekly" | "monthly" | "yearly" | "never";
}
/**
 * Configuration for a dynamic content type in the sitemap.
 */
export interface SitemapContentType {
  /**
   * Content type name.
   */
  name: string;
  /**
   * URL path prefix for this content type.
   */
  basePath: string;
  /**
   * Priority value between 0.0 and 1.0.
   */
  priority: string;
  /**
   * How frequently the page is likely to change.
   */
  changefreq: "always" | "hourly" | "daily" | "weekly" | "monthly" | "yearly" | "never";
}
