import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";

import { compileFromFile } from "json-schema-to-typescript";

import { loadHyperJsonConfig } from "./lib/config.ts";
import { codegenLog } from "./lib/logger.ts";
import { validateContentSchemas } from "./lib/validate.ts";
import { resolveConcurrency, runPool } from "./utils/pool.ts";

export interface HyperJsonCodegenOptions {
  appRootDir: string;
  /**
   * Maximum number of type-generation tasks to run concurrently. Each task
   * compiles one schema in-process via `json-schema-to-typescript`. Defaults to
   * the `HYPERJSON_CONCURRENCY` environment variable, or `cpus().length - 1`
   * (min 1) when unset — leaving a core free to keep the build responsive.
   */
  concurrency?: number;
}

export class HyperJsonCodegen {
  private appRootDir: string;
  private contentDir: string;
  private tsconfigPath: string;
  private generatedTypesPath: string;
  private schemaDirs: string[];
  private concurrency: number;

  constructor(options: HyperJsonCodegenOptions) {
    this.appRootDir = options.appRootDir;
    this.concurrency = resolveConcurrency(options.concurrency);

    const hyperjsonConfig = loadHyperJsonConfig(this.appRootDir);
    this.contentDir = resolve(this.appRootDir, hyperjsonConfig.contentDir);
    this.tsconfigPath = resolve(this.appRootDir, "tsconfig.json");
    this.generatedTypesPath = resolve(this.appRootDir, ".hyper-json/src/content/generated.d.ts");

    const { schemaDirs } = validateContentSchemas(this.contentDir);
    this.schemaDirs = schemaDirs;
  }

  // oxfmt-ignore
  private readonly banner = "/* oxlint-disable */\n/* oxfmt-disable */\n/**\n * --------------------------------------------------------\n *  HyperJson Auto-Generated Types\n * --------------------------------------------------------\n *  This file was automatically generated by HyperJson.\n *  DO NOT EDIT THIS FILE DIRECTLY.\n *\n *  To modify these types, update the corresponding\n *  schema.json file and rebuild the project.\n * --------------------------------------------------------\n */\n";

  private async generateTypesForSchema(schemaDir: string): Promise<void> {
    const schemaPath = resolve(schemaDir, "schema.json");

    const contentDirPrefix = this.contentDir + "/";
    if (!schemaDir.startsWith(contentDirPrefix)) {
      codegenLog.error(`Cannot parse content dir from folder path: ${schemaDir}`);
      return;
    }

    const relPath = schemaDir.slice(contentDirPrefix.length);
    const absPath = join(this.appRootDir, ".hyper-json", "src", "content", relPath);
    mkdirSync(absPath, { recursive: true });

    const typesPath = resolve(absPath, "types.ts");

    try {
      const banner = this.banner;

      const typesContent = await compileFromFile(schemaPath, {
        additionalProperties: false,
        bannerComment: banner,
        cwd: dirname(schemaPath),
      });

      // Post-process to wrap in module declaration
      let codeWithoutBanner = typesContent;
      if (codeWithoutBanner.startsWith(banner)) {
        codeWithoutBanner = codeWithoutBanner.slice(banner.length);
      }

      // Strip 'export ' from interface and type declarations
      codeWithoutBanner = codeWithoutBanner.replace(/^export interface /gm, "interface ");
      codeWithoutBanner = codeWithoutBanner.replace(/^export type /gm, "type ");

      // Indent the code
      const indentedCode = codeWithoutBanner
        .split("\n")
        .map((line) => (line.length > 0 ? `  ${line}` : line))
        .join("\n");

      const finalContent = `${banner}\ndeclare module "@indago/hyper-json" {\n${indentedCode}}\n`;
      writeFileSync(typesPath, finalContent);

      codegenLog.info(`Generated ${typesPath}`);
    } catch (err) {
      codegenLog.error(`[HyperJson] Failed to generate types for ${schemaDir}: ${String(err)}`);
    }
  }

  /**
   * Resolve the import prefixes under which content JSON files are addressable,
   * derived from the consuming app's `tsconfig.json` path aliases. Handles both
   * a direct alias (`@content/*` → `./src/content/*` ⇒ `@content`) and a parent
   * alias (`@/*` → `./src/*` ⇒ `@/content`). Returns an empty array when no
   * alias maps onto the content directory.
   */
  private resolveContentModulePrefixes(): string[] {
    const tsconfig = JSON.parse(readFileSync(this.tsconfigPath, "utf-8"));
    const paths: Record<string, unknown> = tsconfig?.compilerOptions?.paths ?? {};

    // Relative path from appRootDir to contentDir, e.g. "src/content".
    const contentRelDir = relative(this.appRootDir, this.contentDir).replace(/\\/g, "/");

    const normalizeBase = (target: string) => target.replace(/^\.\//, "").replace(/\/\*$/, "");

    // Map: target base → module prefix. Prefer @-prefixed aliases on collision.
    const byTargetBase = new Map<string, string>();

    for (const [alias, targets] of Object.entries(paths)) {
      if (!Array.isArray(targets)) continue;

      const matchedTarget = targets.find((t): t is string => {
        if (typeof t !== "string") return false;

        const base = normalizeBase(t);
        return base === contentRelDir || contentRelDir.startsWith(`${base}/`);
      });

      if (!matchedTarget) continue;

      const targetBase = normalizeBase(matchedTarget);
      const aliasBase = alias.replace(/\/\*$/, "");

      // For a parent alias, append the remainder of the content path to the
      // alias base, e.g. "@" + "/content" → "@/content".
      const contentModulePrefix = aliasBase + contentRelDir.slice(targetBase.length);

      const existing = byTargetBase.get(targetBase);
      if (!existing || (aliasBase.startsWith("@") && !existing.startsWith("@"))) {
        byTargetBase.set(targetBase, contentModulePrefix);
      }
    }

    return [...byTargetBase.values()];
  }

  /** Recursively collect every content JSON file (excluding `schema.json`),
   *  returned as POSIX paths relative to the content directory. */
  private collectContentJsonFiles(): string[] {
    const jsonFiles: string[] = [];

    const scanDir = (dir: string, base: string) => {
      if (!existsSync(dir)) return;

      for (const entry of readdirSync(dir, { withFileTypes: true })) {
        const rel = join(base, entry.name);
        if (entry.isDirectory()) {
          scanDir(join(dir, entry.name), rel);
        } else if (entry.isFile() && entry.name.endsWith(".json") && entry.name !== "schema.json") {
          jsonFiles.push(rel.replace(/\\/g, "/"));
        }
      }
    };
    scanDir(this.contentDir, "");

    return jsonFiles;
  }

  /** Resolve the generated interface name for a content folder from its
   *  `schema.json` `title`, falling back to `any`. */
  private resolveSchemaTypeName(schemaName: string): string {
    const schemaPath = resolve(this.contentDir, schemaName, "schema.json");
    if (!existsSync(schemaPath)) return "any";

    try {
      const schema = JSON.parse(readFileSync(schemaPath, "utf-8"));
      return typeof schema.title === "string" && schema.title ? schema.title : "any";
    } catch {
      return "any"; // Unparseable schema → permissive fallback.
    }
  }

  /** Render a single `declare module` block for an imported content file. */
  private renderAmbientModule(modulePath: string, typeName: string): string {
    return (
      `declare module "${modulePath}" {\n` +
      `  import type { ${typeName} } from "@indago/hyper-json";\n` +
      `  const value: ${typeName};\n` +
      `  export default value;\n` +
      `}\n`
    );
  }

  private generateAmbientModules(): void {
    if (!existsSync(this.tsconfigPath)) return;

    try {
      const prefixes = this.resolveContentModulePrefixes();
      if (prefixes.length === 0) return;

      let generatedDTs = this.banner;

      for (const file of this.collectContentJsonFiles()) {
        // `file` is e.g. "music/en/playlists.json" → folder is the schema name.
        const typeName = this.resolveSchemaTypeName(file.split("/")[0]);
        for (const prefix of prefixes) {
          generatedDTs += this.renderAmbientModule(`${prefix}/${file}`, typeName);
        }
      }

      writeFileSync(this.generatedTypesPath, generatedDTs);
      codegenLog.info(`Generated ${this.generatedTypesPath}`);
    } catch (e) {
      codegenLog.error(`Failed to generate ambient modules: ${String(e)}`);
    }
  }

  public async generate(): Promise<void> {
    const schemaDirs = this.schemaDirs ?? [];

    // Per-schema outputs are fully independent files, so they run in a bounded pool.
    // (The package's own config types are dev-time codegen — `scripts/gen-types.ts`,
    // run on prebuild — never regenerated from a consumer's build.)
    const tasks: (() => Promise<void>)[] = schemaDirs.map(
      (schemaDir) => () => this.generateTypesForSchema(schemaDir),
    );

    const limit = Math.min(this.concurrency, tasks.length);
    codegenLog.info(
      `[HyperJson] Generating TypeScript types for ${schemaDirs.length} schemas ` +
        `using up to ${limit} concurrent workers...`,
    );

    await runPool(tasks, this.concurrency);

    // Ambient module declarations aggregate every content file, so this must
    // run only after all per-schema type generation has settled.
    if (schemaDirs.length > 0) {
      this.generateAmbientModules();
    }
  }
}
