import { contentModules } from "@hyper-down/default";
import { createContentResolver } from "@muttum/hyper-down";

// Browser-safe resolvers: turn a (slug, lang) pair into the MDX component.
// The Next-flavoured `modules.ts` (generated by scripts/codegen.ts) uses explicit
// @next/mdx imports instead of Vite's `import.meta.glob`.
export const getArticleContent = createContentResolver(contentModules["article"]);
export const getRecipeContent = createContentResolver(contentModules["recipe"]);
